name: krsonline
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  google_nav_bar: ^5.0.6
  sliding_up_panel: ^2.0.0+1
  google_fonts: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2
  custom_navigation_bar: ^0.8.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/deco/
    - assets/icon/
    - assets/banner/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-Medium.ttf

    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Bold.ttf
        - asset: assets/font/Inter-Medium.ttf
